import { IPerson } from "../interfaces/IPerson";
import { ListItem } from "./ListItem";

import { ScrollableComponent } from "./ScrollableComponent";

interface PopularPersonListProps {
  personList: IPerson[] | undefined;
  loadingPersonDetails?: boolean;
}

console.log("RENDER - PopularPersonList.tsx");

const MOCK_PERSON_LIST: IPerson[] = [
  {
    adult: false,
    gender: 2,
    id: 1253360,
    known_for: [
      {
        backdrop_path: "/6Lw54zxm6BAEKJeGlabyzzR5Juu.jpg",
        first_air_date: "2019-11-12",
        genre_ids: [10765, 10759, 18],
        id: 82856,
        media_type: "tv",
        name: "The Mandalorian",
        origin_country: ["US"],
        original_language: "en",
        original_name: "The Mandalorian",
        overview:
          "A saga de um guerreiro solitário, que também é um mercenário e pistoleiro, viajando pelos territórios esquecidos e marginais do espaço, logo após a queda do Império e antes da criação da temida Primeira Ordem.",
        poster_path: "/sWgBv7LV2PRoQgkxwlibdGXKz1S.jpg",
        vote_average: 8.5,
        vote_count: 8541,
      },
      {
        backdrop_path: "/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg",
        first_air_date: "2023-01-15",
        genre_ids: [18],
        id: 100088,
        media_type: "tv",
        name: "The Last of Us",
        origin_country: ["US"],
        original_language: "en",
        original_name: "The Last of Us",
        overview:
          "Situado duas décadas após a implosão de nossa sociedade, o drama seguirá Joel, um sobrevivente difícil, que é contratado para contrabandear uma garota de 14 anos chamada Ellie para fora de uma zona de quarentena opressiva. O que começa como um pequeno trabalho logo se torna uma jornada brutal e de partir o coração, já que os dois precisam atravessar os Estados Unidos e dependem um do outro para sobreviver.",
        poster_path: "/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg",
        vote_average: 8.8,
        vote_count: 2567,
      },
      {
        adult: false,
        backdrop_path: "/z7noaCJ4KtmhwHw7QcNtnMMo4Qy.jpg",
        genre_ids: [28, 53, 80],
        id: 345887,
        media_type: "movie",
        original_language: "en",
        original_title: "The Equalizer 2",
        overview:
          "Criminosos assassinam Susan Plummer, a melhor amiga de Robert McCall e sua ex-colega de trabalho. Obcecado, Robert pensa apenas em eliminar o bando de assassinos profissionais que destruiu sua vida.",
        poster_path: "/REWunAyKGCbxvg2UJGMEHuQd2c.jpg",
        release_date: "2018-07-19",
        title: "O Protetor 2",
        video: false,
        vote_average: 6.7,
        vote_count: 4320,
      },
    ],
    known_for_department: "Acting",
    name: "Pedro Pascal",
    popularity: 386.967,
    profile_path: "/nms0d0ExYtiOke82oqr3vOb3smF.jpg",
  },
  {
    adult: false,
    gender: 2,
    id: 58021,
    known_for: [
      {
        adult: false,
        backdrop_path: "/6UDep1cxHQqrNFhSW4ZNQLW3Alr.jpg",
        genre_ids: [18, 36, 10749],
        id: 9453,
        media_type: "movie",
        original_language: "en",
        original_title: "Caligola",
        overview:
          "Calígula é uma das mais polêmicas produções do cinema, o único que mostra o show de perversões que o Império Romano escondia. Este filme conta a história de Calígula, o mais louco dos imperadores, que mantinha um bizarro caso sexual com sua irmã e era casado com a mais infame das prostitutas. Ao mesmo tempo que Calígula vivia cercado de bajuladores, tinha também inimigos perigosos, loucos para vê-lo longe do poder.",
        poster_path: "/5TpS5yJQT64lSglaD7D1AvhHKw2.jpg",
        release_date: "1979-08-14",
        title: "Calígula",
        video: false,
        vote_average: 6,
        vote_count: 646,
      },
      {
        adult: false,
        backdrop_path: "/iHDermFVn4DiShm5cvUK0f0rW2A.jpg",
        genre_ids: [18, 10749],
        id: 28468,
        media_type: "movie",
        original_language: "it",
        original_title: "La chiave",
        overview:
          "Descoberta a admiração secreta de sua esposa para o seu futuro genro – Laszlo -, Nino toma consciência da diminuição de sua libido, e resolve manipular a aproximação entre eles através de seu diário, que é lido às escondidas por sua esposa. Esta, sempre muito recatada, vai, aos poucos, cedendo aos seus desejos sexuais e deixando para trás seu comportamento contido, tanto nos encontros com Laszlo, quanto com seu marido. Nada é capaz de deter sua libertação sexual, nem mesmo a filha, noiva de Laszlo.",
        poster_path: "/rj8EOr3miAwYXBR3AVr3nYNa69o.jpg",
        release_date: "1983-10-19",
        title: "A Chave",
        video: false,
        vote_average: 5.9,
        vote_count: 332,
      },
      {
        adult: false,
        backdrop_path: "/9CkI4VsYF8qJWfZpPqwZnBctb3M.jpg",
        genre_ids: [18],
        id: 50270,
        media_type: "movie",
        original_language: "it",
        original_title: "Paprika",
        overview:
          "Paprika é o nome de guerra de uma garota que aceita se prostituir apenas para conseguir dinheiro e financiar o namorado em um novo negócio. Inicialmente tímida e pouco experiente, logo ela se torna uma das estrelas do prostíbulo. Sua vida na prostituição e todos os eventos nele são centrais. Claro que a garota está presa ainda por seu namorado Nino. Ele a convenceu a trabalhar em um bordel para que ele possa pagar suas dívidas e depois morar juntos. Infelizmente, parece que Nino só quer ganhar dinheiro com ela. O problema é que ela acaba se apaixonando por um dos clientes.",
        poster_path: "/h9n9icL3iqaVyw9t9JQaaPhfrsn.jpg",
        release_date: "1991-02-13",
        title: "O Bordel de Paprika",
        video: false,
        vote_average: 7,
        vote_count: 327,
      },
    ],
    known_for_department: "Directing",
    name: "Tinto Brass",
    popularity: 270.156,
    profile_path: "/80Uuq79rcYL1FgBPHAEHzAACQFa.jpg",
  },
  {
    adult: false,
    gender: 1,
    id: 15737,
    known_for: [
      {
        backdrop_path: "/8V1XPEDLtJoxOWlE6gYzn2sQaMp.jpg",
        first_air_date: "2013-09-12",
        genre_ids: [18, 80],
        id: 60574,
        media_type: "tv",
        name: "Peaky Blinders: Sangue, Apostas e Navalhas",
        origin_country: ["GB"],
        original_language: "en",
        original_name: "Peaky Blinders",
        overview:
          "Thomas Shelby e seus irmãos retornam a Birmingham depois de servir no exército britânico durante a Primeira Guerra Mundial. Os Peaky Blinders, a gangue na qual Thomas é líder, controlam a cidade de Birmingham. Mas, como as ambições de Shelby se estendem para além de Birmingham, ele planeja construir o império de negócios que criou e impedir qualquer um que atrapalhar.",
        poster_path: "/i0uajcHH9yogXMfDHpOXexIukG9.jpg",
        vote_average: 8.5,
        vote_count: 8212,
      },
      {
        adult: false,
        backdrop_path: "/hoQhlAskVNgLQhArnH7reWP4pUp.jpg",
        genre_ids: [28, 12, 53],
        id: 37724,
        media_type: "movie",
        original_language: "en",
        original_title: "Skyfall",
        overview:
          "Após uma missão mal sucedida de James Bond, a identidade de agentes secretos é revelada e o M16, atacado. Ajudado por um agente de campo, Bond deverá seguir a trilha de Silva, um homem que habita o passado de M e que tem contas a acertar.",
        poster_path: "/1U1gkQynuQRNsZ8zm13zSCGOFAj.jpg",
        release_date: "2012-10-24",
        title: "007: Operação Skyfall",
        video: false,
        vote_average: 7.2,
        vote_count: 14107,
      },
      {
        adult: false,
        backdrop_path: "/urDWNffjwmNi5IQaezw9GwqkUXa.jpg",
        genre_ids: [12, 14],
        id: 767,
        media_type: "movie",
        original_language: "en",
        original_title: "Harry Potter and the Half-Blood Prince",
        overview:
          "À medida que Lorde Voldemort aperta seu cerco ao mundo dos Trouxas e dos feiticeiros. Hogwarts deixou de ser um paraiso protegido. Harry suspeita que existam perigos até mesmo dentro do castelo, mas Dumbledore está mais preocupado para a batalha final que está próximo de se iniciar. Juntos, eles se esforçam para descobrir a chave que desbloqueia as defesas de Voldemort e, para isso, Dumbledore recruta seu velho amigo horace slughorn, quem, ele acredita, possuí informações valiosas a respeito. Mesmo quando um confronto decisivo se aproxima, há tempo para romance nos corações de Harry, Ron, Hermione e seus colegas de classe. O amor está no ar, mas o perigo também e Hogwarts poderá nunca mais ser a mesma.",
        poster_path: "/zSKNXome5vmnBVQCmpWN8do7Bpa.jpg",
        release_date: "2009-07-07",
        title: "Harry Potter e o Enigma do Príncipe",
        video: false,
        vote_average: 7.7,
        vote_count: 17413,
      },
    ],
    known_for_department: "Acting",
    name: "Helen McCrory",
    popularity: 200.247,
    profile_path: "/3FyO7Z8WigeCQsUpW4B1x3qfmFx.jpg",
  },
  {
    adult: false,
    gender: 1,
    id: 2710789,
    known_for: [
      {
        adult: false,
        backdrop_path: "/rnWEut44AFaC4G7H3nSwzKVIyV8.jpg",
        genre_ids: [18, 10749],
        id: 724106,
        media_type: "movie",
        original_language: "ko",
        original_title: "18금 아이돌 승하의 섹스 스캔들",
        overview: "",
        poster_path: "/btpk0Y0m9MjvMCfgrW0i0d7fpd1.jpg",
        release_date: "2020-07-17",
        title: "18금 아이돌 승하의 섹스 스캔들",
        video: false,
        vote_average: 6.9,
        vote_count: 27,
      },
      {
        adult: false,
        backdrop_path: "/lQYIamZ7SZR4Ufq7mKUwPZtBYWL.jpg",
        genre_ids: [18],
        id: 852370,
        media_type: "movie",
        original_language: "ko",
        original_title: "아이돌 승하의 19금 AV를 찍자",
        overview: "",
        poster_path: "/4CVYNzGwTMgOKxycg2LQO9slwfH.jpg",
        release_date: "2021-06-24",
        title: "아이돌 승하의 19금 AV를 찍자",
        video: false,
        vote_average: 7.8,
        vote_count: 12,
      },
      {
        adult: false,
        backdrop_path: "/xZ02qIyNEPXSDJn89LFeQS3FuvX.jpg",
        genre_ids: [18, 10749],
        id: 724108,
        media_type: "movie",
        original_language: "ko",
        original_title: "18금 아이돌 승하의 화려한 외출",
        overview: "",
        poster_path: "/l0jd4v2490rC9oqwnEOVJ6KNK3x.jpg",
        release_date: "2020-07-01",
        title: "18금 아이돌 승하의 화려한 외출",
        video: false,
        vote_average: 7.2,
        vote_count: 10,
      },
    ],
    known_for_department: "Acting",
    name: "Seung Ha",
    popularity: 198.815,
    profile_path: "/8dCFK8FDFQbYFZvzAE9IIeaDMKo.jpg",
  },
  {
    adult: false,
    gender: 1,
    id: 224513,
    known_for: [
      {
        adult: false,
        backdrop_path: "/sAtoMqDVhNDQBc3QJL3RF6hlhGq.jpg",
        genre_ids: [878, 18],
        id: 335984,
        media_type: "movie",
        original_language: "en",
        original_title: "Blade Runner 2049",
        overview:
          "Após descobrir um segredo enterrado há muito tempo, que ameaça o que resta da sociedade, um novo policial embarca na busca de Rick Deckard, que está desaparecido há 30 anos.",
        poster_path: "/qWD9E0Wgn8w6nMMutCNFAUiSHrX.jpg",
        release_date: "2017-10-04",
        title: "Blade Runner 2049",
        video: false,
        vote_average: 7.5,
        vote_count: 11646,
      },
      {
        adult: false,
        backdrop_path: "/4HWAQu28e2yaWrtupFPGFkdNU7V.jpg",
        genre_ids: [35, 80, 9648],
        id: 546554,
        media_type: "movie",
        original_language: "en",
        original_title: "Knives Out",
        overview:
          "Após comemorar 85 anos de idade, o famoso escritor de histórias policiais Harlan Thrombey é encontrado morto dentro de sua propriedade. Logo, o detetive Benoit Blanc é contratado para investigar o caso e descobre que, entre os funcionários misteriosos e a família conflituosa de Harlan, todos podem ser considerados suspeitos do crime.",
        poster_path: "/y9bPnWN7M0SmDvh4Nns0R4Jc2Jn.jpg",
        release_date: "2019-11-27",
        title: "Entre Facas e Segredos",
        video: false,
        vote_average: 7.9,
        vote_count: 10456,
      },
      {
        adult: false,
        backdrop_path: "/oNoprEND25zXR6Fns8cIZUkuoMc.jpg",
        genre_ids: [35, 80, 18],
        id: 308266,
        media_type: "movie",
        original_language: "en",
        original_title: "War Dogs",
        overview:
          "Após uma experiência mal sucedida em fazer negócios com o governo, dois amigos moradores de Miami Beach, que levam uma vida tranquila e que só queriam dinheiro para sustentar seu vício em maconha, descobrem que existe um mercado ilícito em expansão com a venda de armas para o exterior. Ao fechar um contrato de 300 milhões de dólares, eles terão de ir para o Afeganistão acompanhar a explosiva transação pessoalmente.",
        poster_path: "/uv9g0yF3z10tWWq24OQewQf6r5e.jpg",
        release_date: "2016-08-17",
        title: "Cães de Guerra",
        video: false,
        vote_average: 6.9,
        vote_count: 4282,
      },
    ],
    known_for_department: "Acting",
    name: "Ana de Armas",
    popularity: 196.365,
    profile_path: "/vkoSSVrGxFYvtr2uUdz99ENXF1v.jpg",
  },
  {
    adult: false,
    gender: 1,
    id: 974169,
    known_for: [
      {
        backdrop_path: "/iHSwvRVsRyxpX7FE7GbviaDvgGZ.jpg",
        first_air_date: "2022-11-23",
        genre_ids: [10765, 9648, 35],
        id: 119051,
        media_type: "tv",
        name: "Wandinha",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Wednesday",
        overview:
          "Inteligente, sarcástica e apática, Wandinha Addams pode estar meio morta por dentro, mas na Escola Nunca Mais ela vai fazer amigos, inimigos e investigar assassinatos.",
        poster_path: "/ooBR3qulC40ws0QkYBUAYFKmLRE.jpg",
        vote_average: 8.6,
        vote_count: 6644,
      },
      {
        adult: false,
        backdrop_path: "/21ldFAokKVjwzi1SHXoPb5gc7md.jpg",
        genre_ids: [27, 9648, 53],
        id: 760104,
        media_type: "movie",
        original_language: "en",
        original_title: "X",
        overview:
          "Em 1979, um grupo de jovens cineastas se propôs a fazer um filme adulto na zona rural do Texas, mas quando seus solitários e idosos anfitriões os pegam em flagrante, o elenco se vê lutando por suas vidas.",
        poster_path: "/As5dKK7fLOlCyVwjqoW5pyiDz6D.jpg",
        release_date: "2022-03-17",
        title: "X: A Marca da Morte",
        video: false,
        vote_average: 6.8,
        vote_count: 1768,
      },
      {
        adult: false,
        backdrop_path: "/ifUfE79O1raUwbaQRIB7XnFz5ZC.jpg",
        genre_ids: [27, 9648, 53],
        id: 646385,
        media_type: "movie",
        original_language: "en",
        original_title: "Scream",
        overview:
          "Vinte e cinco anos após uma série de crimes brutais chocar a tranquila Woodsboro, um novo assassino se apropria da máscara de Ghostface e começa a perseguir um grupo de adolescentes para trazer à tona segredos do passado mortal da cidade.",
        poster_path: "/oadFpqhJ26yxqIlYcGioZ2W3EHN.jpg",
        release_date: "2022-01-12",
        title: "Pânico",
        video: false,
        vote_average: 6.7,
        vote_count: 2161,
      },
    ],
    known_for_department: "Acting",
    name: "Jenna Ortega",
    popularity: 188.371,
    profile_path: "/q1NRzyZQlYkxLY07GO9NVPkQnu8.jpg",
  },
  {
    adult: false,
    gender: 2,
    id: 1907997,
    known_for: [
      {
        adult: false,
        genre_ids: [10749],
        backdrop_path: null,
        id: 721187,
        media_type: "movie",
        original_language: "ko",
        original_title: "미용실 : 특별한 서비스 4",
        overview: "",
        poster_path: "/nJpoe1CKuiqh90qUliO6qHCeNYI.jpg",
        release_date: "2022-12-01",
        title: "미용실 : 특별한 서비스 4",
        video: false,
        vote_average: 6.6,
        vote_count: 10,
      },
      {
        adult: false,
        backdrop_path: "/35V5CNHsJAcu1k5YtRCasn3sUtR.jpg",
        genre_ids: [10749],
        id: 685090,
        media_type: "movie",
        original_language: "ko",
        original_title: "여선생 3",
        overview: "",
        poster_path: "/ltT8NysDFAwRNyysIubYRMnUqaG.jpg",
        release_date: "2020-03-20",
        title: "여선생 3",
        video: false,
        vote_average: 5.7,
        vote_count: 7,
      },
      {
        adult: false,
        backdrop_path: "/essb3JUruLtwNsiNVrUmVfOatHJ.jpg",
        genre_ids: [18, 10749],
        id: 725405,
        media_type: "movie",
        original_language: "ko",
        original_title: "옆방에 일본여자가 싼다",
        overview: "",
        poster_path: "/ltsm79ByVGCfzlKYD91lcQNjK8o.jpg",
        release_date: "2020-07-09",
        title: "옆방에 일본여자가 싼다",
        video: false,
        vote_average: 7,
        vote_count: 11,
      },
    ],
    known_for_department: "Acting",
    name: "Min Do-yoon",
    popularity: 179.716,
    profile_path: "/bHHn3krbHyxQIWb4JbHkPlV6Uu1.jpg",
  },
  {
    adult: false,
    gender: 1,
    id: 3194176,
    known_for: [
      {
        adult: false,
        backdrop_path: "/27bkw4o1zhjQAM4WIFQPohiph1X.jpg",
        genre_ids: [18],
        id: 931599,
        media_type: "movie",
        original_language: "tl",
        original_title: "Silip Sa Apoy",
        overview:
          "Dê uma olhada na vida de uma dona de casa infeliz que encontra o amor apaixonado de seu vizinho e como seu caso os aproxima do fogo.",
        poster_path: "/9grG4PVppBWqKs2hrKMEr6j3RWS.jpg",
        release_date: "2022-01-28",
        title: "Silip Sa Apoy",
        video: false,
        vote_average: 6.3,
        vote_count: 23,
      },
      {
        adult: false,
        backdrop_path: "/ru5zAV1Ij6bQGedBkczqhiBmjzn.jpg",
        genre_ids: [18],
        id: 1029446,
        media_type: "movie",
        original_language: "tl",
        original_title: "Selina's Gold",
        overview:
          "O pai de Selina a vende para Tiago, que a torna uma escrava sexual. Com a ajuda de Domeng, o escravo cego de Tiago, ela planeja uma saída deste inferno.",
        poster_path: "/4a0X2GKDmhhp1U2FUKtKY6uNQHL.jpg",
        release_date: "2022-10-28",
        title: "Selina's Gold",
        video: false,
        vote_average: 7,
        vote_count: 22,
      },
      {
        adult: false,
        backdrop_path: "/ougkufYSiruP8jrEHQanXN7DxRv.jpg",
        genre_ids: [18, 10749],
        id: 893694,
        media_type: "movie",
        original_language: "tl",
        original_title: "Eva",
        overview:
          "Quando Eva se envolve em um sexo a três com um criado e sua patroa, ela percebe que tem que escolher apenas um entre eles.",
        poster_path: "/3Fe75Lf6VT7wvYMK8YQhRusbJjc.jpg",
        release_date: "2021-12-24",
        title: "Eva",
        video: false,
        vote_average: 5.6,
        vote_count: 7,
      },
    ],
    known_for_department: "Acting",
    name: "Angeli Khang",
    popularity: 171.906,
    profile_path: "/7vrTWF8PxQogF6o9ORZprYQoDOr.jpg",
  },
  {
    adult: false,
    gender: 1,
    id: 6161,
    known_for: [
      {
        adult: false,
        backdrop_path: "/vVBcIN68kFq681b4lObiNJhEVro.jpg",
        genre_ids: [18, 10749],
        id: 453,
        media_type: "movie",
        original_language: "en",
        original_title: "A Beautiful Mind",
        overview:
          "John Nash (Russell Crowe) é um gênio da matemática que, aos 21 anos, formulou um teorema que provou sua genialidade e o tornou aclamado no meio onde atuava. Mas aos poucos o belo e arrogante Nash se transforma em um sofrido e atormentado homem, que chega até mesmo a ser diagnosticado como esquizofrênico pelos médicos que o tratam. Porém, após anos de luta para se recuperar, ele consegue retornar à sociedade e acaba sendo premiado com o Nobel.",
        poster_path: "/8K5W9QnNT7r1V9GuJ5z5KlrROkd.jpg",
        release_date: "2001-12-11",
        title: "Uma Mente Brilhante",
        video: false,
        vote_average: 7.9,
        vote_count: 9113,
      },
      {
        adult: false,
        backdrop_path: "/7jR6xSOqnWCrm3OGhm06Y8jGCYS.jpg",
        genre_ids: [80, 18],
        id: 641,
        media_type: "movie",
        original_language: "en",
        original_title: "Requiem for a Dream",
        overview:
          "Enquanto o filho lida com sua própria batalha contra as drogas, Sara é convidada para participar de seu programa de TV favorito. Para poder usar o vestido preferido, começa a tomar pílulas para emagrecer e fica viciada.",
        poster_path: "/1XoWfP4l4X7sQMH8dhVQOWc91Pd.jpg",
        release_date: "2000-10-06",
        title: "Réquiem para um Sonho",
        video: false,
        vote_average: 8,
        vote_count: 8732,
      },
      {
        adult: false,
        backdrop_path: "/5z75Q6nqgwgYfpMB9fVHQcw9gMz.jpg",
        genre_ids: [18, 12],
        id: 86834,
        media_type: "movie",
        original_language: "en",
        original_title: "Noah",
        overview:
          "Noé vive com a esposa Naameh e os filhos Sem, Cam e Jafé em um mundo devastado pelo pecado, onde os homens perseguem e matam uns aos outros. Um dia, Noé recebe uma missão divina do Criador: construir uma imensa arca, que abrigará os animais durante um dilúvio que acabará com a vida na Terra, de forma que a visão do Criador possa ser, enfim, resgatada.",
        poster_path: "/nVdsXW3oJKBCMpNVZcg8teCk0cS.jpg",
        release_date: "2014-03-07",
        title: "Noé",
        video: false,
        vote_average: 5.6,
        vote_count: 5653,
      },
    ],
    known_for_department: "Acting",
    name: "Jennifer Connelly",
    popularity: 162.523,
    profile_path: "/opBts8lC3ZhK4BQwl8ztczehsFQ.jpg",
  },
  {
    adult: false,
    gender: 1,
    id: 1373737,
    known_for: [
      {
        adult: false,
        backdrop_path: "/8yE6wv1l570zWyh6zmkFxysw3Kc.jpg",
        genre_ids: [27, 18, 9648],
        id: 530385,
        media_type: "movie",
        original_language: "en",
        original_title: "Midsommar",
        overview:
          "Dani e Christian formam um jovem casal americano com um relacionamento prestes a desmoronar. Mas depois que uma tragédia familiar os mantém juntos, Dani, que está de luto, convida-se para se juntar a Christian e seus amigos em uma viagem para um festival de verão único em uma remota vila sueca. O que começa como férias despreocupadas de verão em uma terra de luz eterna toma um rumo sinistro quando os moradores do vilarejo convidam o grupo a participar de festividades que tornam o paraíso pastoral cada vez mais preocupante e visceralmente perturbador.",
        poster_path: "/sZ6Bjq1VVfiTrALlev0ganz7uka.jpg",
        release_date: "2019-07-03",
        title: "Midsommar: O Mal Não Espera a Noite",
        video: false,
        vote_average: 7.2,
        vote_count: 5672,
      },
      {
        adult: false,
        backdrop_path: "/keIxh0wPr2Ymj0Btjh4gW7JJ89e.jpg",
        genre_ids: [28, 12, 878],
        id: 497698,
        media_type: "movie",
        original_language: "en",
        original_title: "Black Widow",
        overview:
          "Natasha Romanoff, também conhecida como Viúva Negra, confronta o lado mais sombrio de sua história quando surge uma perigosa conspiração ligada ao seu passado. Perseguida por uma força implacável disposta a tudo para destruí-la, Natasha precisa agora lidar com seu passado como espiã e com as relações que deixou para trás muito antes de se tornar uma Vingadora.",
        poster_path: "/rKq1Vlw0Bqe2EEvdmIkkkgPQAGf.jpg",
        release_date: "2021-07-07",
        title: "Viúva Negra",
        video: false,
        vote_average: 7.4,
        vote_count: 8732,
      },
      {
        adult: false,
        backdrop_path: "/sOJqNAx4RFrCRn8HS99LEc8aenI.jpg",
        genre_ids: [18, 10749, 36],
        id: 331482,
        media_type: "movie",
        original_language: "en",
        original_title: "Little Women",
        overview:
          "As irmãs Jo, Beth, Meg e Amy amadurecem na virada da adolescência para a vida adulta enquanto os Estados Unidos atravessam a Guerra Civil. Com personalidades completamente diferentes, elas enfrentam os desafios de crescer unidas pelo amor que nutrem umas pelas outras.",
        poster_path: "/1dwhsiuvNyQmA9ytp3T40uz4MOv.jpg",
        release_date: "2019-12-25",
        title: "Adoráveis Mulheres",
        video: false,
        vote_average: 7.9,
        vote_count: 5358,
      },
    ],
    known_for_department: "Acting",
    name: "Florence Pugh",
    popularity: 161.99,
    profile_path: "/f8e41Oon18FiEZr4zgyJDVUqOeh.jpg",
  },
  {
    adult: false,
    gender: 2,
    id: 976,
    known_for: [
      {
        adult: false,
        backdrop_path: "/ysKahAEPP8h6MInuLjr0xuZOTjh.jpg",
        genre_ids: [80, 35],
        id: 107,
        media_type: "movie",
        original_language: "en",
        original_title: "Snatch",
        overview:
          "Quando o ladrão de jóias Franky Quatro Dedos faz uma rápida parada em Londres, antes de entregar um enorme diamante roubado para o seu chefe em Nova York, ele não tinha a menor idéia da avalanche de sinistros e cômicos acontecimentos que abalariam os mundo do boxe, dos ciganos irlandeses, das lojas de penhores, das fazendas de porcos e... de um cão vira-latas.",
        poster_path: "/fnbXu4HYTsOvbibOjnq8zF0Q7pe.jpg",
        release_date: "2000-09-01",
        title: "Snatch: Porcos e Diamantes",
        video: false,
        vote_average: 7.8,
        vote_count: 7900,
      },
      {
        adult: false,
        backdrop_path: "/ibKeXahq4JD63z6uWQphqoJLvNw.jpg",
        genre_ids: [28, 878, 27],
        id: 345940,
        media_type: "movie",
        original_language: "en",
        original_title: "The Meg",
        overview:
          "Na fossa mais profunda do Oceano Pacífico, a tripulação de um submarino fica presa dentro do local após ser atacada por uma criatura pré-histórica que se achava estar extinta, um tubarão de mais de 20 metros de comprimento, o Megalodon. Para salvá-los, um oceanógrafo chinês contrata Jonas Taylor, um mergulhador especializado em resgates em água profundas que já encontrou com a criatura anteriormente.",
        poster_path: "/wrJkShDPK4TcV0nHix3HASEmkul.jpg",
        release_date: "2018-08-09",
        title: "Megatubarão",
        video: false,
        vote_average: 6.2,
        vote_count: 6301,
      },
      {
        adult: false,
        backdrop_path: "/jzdnhRhG0dsuYorwvSqPqqnM1cV.jpg",
        genre_ids: [28, 80, 53],
        id: 337339,
        media_type: "movie",
        original_language: "en",
        original_title: "The Fate of the Furious",
        overview:
          "Depois que Brian e Mia se aposentaram, e o resto da equipe foi exonerado, Dom e Letty estão em lua de mel e levam uma vida pacata e completamente normal. Mas a adrenalina do passado volta com tudo quando uma mulher misteriosa faz com que Dom retorne ao mundo do crime e da velocidade.",
        poster_path: "/5L2IpMfGFfwOmxNdIJeJtdlz03.jpg",
        release_date: "2017-04-12",
        title: "Velozes & Furiosos 8",
        video: false,
        vote_average: 6.9,
        vote_count: 9355,
      },
    ],
    known_for_department: "Acting",
    name: "Jason Statham",
    popularity: 155.137,
    profile_path: "/lldeQ91GwIVff43JBrpdbAAeYWj.jpg",
  },
  {
    adult: false,
    gender: 3,
    id: 3505950,
    known_for: [
      {
        adult: false,
        backdrop_path: "/ihBrgKx7IuOptUYcblRJHAraRM0.jpg",
        genre_ids: [18],
        id: 901563,
        media_type: "movie",
        original_language: "fr",
        original_title: "Close",
        overview:
          "A amizade entre dois meninos de treze anos, Leo e Rémi, acaba de repente. Sem entender o que aconteceu, Léo procura Sophie, mãe de Rémi.",
        poster_path: "/247j36lEhkTGYTjFE3oWKVKMwVJ.jpg",
        release_date: "2022-11-01",
        title: "Close",
        video: false,
        vote_average: 7.8,
        vote_count: 255,
      },
    ],
    known_for_department: "Acting",
    name: "Eden Dambrine",
    popularity: 151.628,
    profile_path: "/9u8byzr9LpFvuvYk7bep6l8U5Ow.jpg",
  },
  {
    adult: false,
    gender: 1,
    id: 1620,
    known_for: [
      {
        adult: false,
        backdrop_path: "/tt79dbOPd9Z9ykEOpvckttgYXwH.jpg",
        genre_ids: [28, 12, 878],
        id: 545611,
        media_type: "movie",
        original_language: "en",
        original_title: "Everything Everywhere All at Once",
        overview:
          "Uma imigrante chinesa parte rumo a uma aventura onde, sozinha, precisará salvar o mundo, explorando outros universos e outras vidas que poderia ter vivido. Contudo, as coisas se complicam quando ela fica presa nessa infinidade de possibilidades sem conseguir retornar para casa.",
        poster_path: "/2dSZQGwijlXvMSyuGe0FSgrXnv0.jpg",
        release_date: "2022-03-24",
        title: "Tudo em Todo o Lugar ao Mesmo Tempo",
        video: false,
        vote_average: 8,
        vote_count: 3608,
      },
      {
        adult: false,
        backdrop_path: "/ylZ06kRUF2JKkrCG2E3qn5D9w8L.jpg",
        genre_ids: [12, 18, 28, 10749],
        id: 146,
        media_type: "movie",
        original_language: "zh",
        original_title: "卧虎藏龍",
        overview:
          "A história de duas mulheres, ambas exímias lutadoras, cujos destinos se tocam em meio a Dinastia Ching. Uma tenta se ver livre do constrangimento imposto pela sociedade local, mesmo que isso a obrigue a deixar uma vida aristocrática por outra de crimes e paixão. A outra, em sua cruzada de honra e justiça, apenas descobre as consequências do amor tarde demais. Os destinos de ambas as conduzirão uma violenta e surpreendente jornada, que irá forçá-las a fazer uma escolha que poderá mudar suas vidas.",
        poster_path: "/6ZPfaWGAir5qgGK0VfBOzOqB3yF.jpg",
        release_date: "2000-07-06",
        title: "O Tigre e o Dragão",
        video: false,
        vote_average: 7.4,
        vote_count: 2763,
      },
      {
        adult: false,
        backdrop_path: "/yUHP5AectnhcG4dWJ53L3uQvOgu.jpg",
        genre_ids: [12, 28, 53],
        id: 714,
        media_type: "movie",
        original_language: "en",
        original_title: "Tomorrow Never Dies",
        overview:
          "James Bond descobre que o magnata da mídia Elliot Carver colocou em prática um plano para manipular as superpotências e expandir seus negócios. O agente deve impedir que essa ideia doentia provoque uma nova guerra mundial.",
        poster_path: "/cURZ8FpxFzwZHCL07ABXJCVnORc.jpg",
        release_date: "1997-12-11",
        title: "007: O Amanhã Nunca Morre",
        video: false,
        vote_average: 6.3,
        vote_count: 2663,
      },
    ],
    known_for_department: "Acting",
    name: "Michelle Yeoh",
    popularity: 142.425,
    profile_path: "/6oxvfyrrM3YmhgFZSqc8ESqPZoC.jpg",
  },
  {
    adult: false,
    gender: 2,
    id: 86654,
    known_for: [
      {
        adult: false,
        backdrop_path: "/rLo9T9jEg67UZPq3midjLnTUYYi.jpg",
        genre_ids: [18, 10402, 36],
        id: 614934,
        media_type: "movie",
        original_language: "en",
        original_title: "Elvis",
        overview:
          "A história de vida de Elvis Presley vista através do relacionamento complicado com seu empresário enigmático, o coronel Tom Parker.",
        poster_path: "/qBOKWqAFbveZ4ryjJJwbie6tXkQ.jpg",
        release_date: "2022-06-22",
        title: "Elvis",
        video: false,
        vote_average: 7.7,
        vote_count: 2375,
      },
      {
        adult: false,
        backdrop_path: "/oRiUKwDpcqDdoLwPoA4FIRh3hqY.jpg",
        genre_ids: [35, 18, 53],
        id: 466272,
        media_type: "movie",
        original_language: "en",
        original_title: "Once Upon a Time… in Hollywood",
        overview:
          "Los Angeles, 1969. Rick Dalton é um ator de TV que, juntamente com seu dublê, está decidido a fazer o nome em Hollywood. Para tanto, ele conhece muitas pessoas influentes na indústria cinematográfica, o que os acaba levando aos assassinatos realizados por Charles Manson na época, entre eles o da atriz Sharon Tate, que na época estava grávida do diretor Roman Polanski.",
        poster_path: "/h30FdikGNkrT6loajaO9G1HHjz0.jpg",
        release_date: "2019-07-24",
        title: "Era Uma Vez em… Hollywood",
        video: false,
        vote_average: 7.4,
        vote_count: 11582,
      },
      {
        backdrop_path: "/8RNoJJn2S8DlA331OyIqTh3zr68.jpg",
        first_air_date: "2016-01-05",
        genre_ids: [10759, 10765],
        id: 64122,
        media_type: "tv",
        name: "As Crônicas de Shannara",
        origin_country: ["US"],
        original_language: "en",
        original_name: "The Shannara Chronicles",
        overview:
          "Após a destruição da civilização humana, três jovens heróis tornam-se a última esperança de salvação para a Terra quando demônios ameaçam acabar com o planeta.",
        poster_path: "/mumIOwzoVjMr9aEANbpWyIlYDir.jpg",
        vote_average: 7,
        vote_count: 804,
      },
    ],
    known_for_department: "Acting",
    name: "Austin Butler",
    popularity: 132.047,
    profile_path: "/zyizc36OayhIn3STXR8HXP0nnVm.jpg",
  },
  {
    adult: false,
    gender: 2,
    id: 1908004,
    known_for: [
      {
        adult: false,
        backdrop_path: "/k0b33UJhJWC0TUjJGnQPm4spVaf.jpg",
        genre_ids: [10749],
        id: 660039,
        media_type: "movie",
        original_language: "ko",
        original_title: "옆집누나의맛",
        overview: "",
        poster_path: "/f4Y5auc3FgaBJ0X2kjKIwgCecQZ.jpg",
        release_date: "2019-12-30",
        title: "The Taste of Next Door Sister",
        video: false,
        vote_average: 3.4,
        vote_count: 13,
      },
      {
        adult: false,
        backdrop_path: "/bgOzVXLt2f1UcWi4RNVTLUOnJMa.jpg",
        genre_ids: [10749],
        id: 471831,
        media_type: "movie",
        original_language: "ko",
        original_title: "일대일",
        overview: "",
        poster_path: "/xQ7A6bubHPxKSOJjiZdx0z33fKH.jpg",
        release_date: "2017-08-01",
        title: "일대일",
        video: false,
        vote_average: 5.1,
        vote_count: 10,
      },
      {
        adult: false,
        backdrop_path: "/saiXZOzwSIZEw7N1N8cKaqsBgJ.jpg",
        genre_ids: [10749],
        id: 569715,
        media_type: "movie",
        original_language: "ko",
        original_title: "맛있는 세자매",
        overview: "",
        poster_path: "/q85VR4nlUUu9tERLUvPFyq2WB8c.jpg",
        release_date: "2018-10-04",
        title: "맛있는 세자매",
        video: false,
        vote_average: 4.3,
        vote_count: 7,
      },
    ],
    known_for_department: "Acting",
    name: "Sang Woo",
    popularity: 116.845,
    profile_path: "/p9uQlfp5BcGxkbMhmg6bqrRsbch.jpg",
  },
  {
    adult: false,
    gender: 2,
    id: 31,
    known_for: [
      {
        adult: false,
        backdrop_path: "/3h1JZGDhZ8nzxdgvkxha0qBqi05.jpg",
        genre_ids: [35, 18, 10749],
        id: 13,
        media_type: "movie",
        original_language: "en",
        original_title: "Forrest Gump",
        overview:
          "Quarenta anos da história dos Estados Unidos, vistos pelos olhos de Forrest Gump, um rapaz com QI abaixo da média e com boas intenções. Por obra do acaso, ele consegue participar de momentos cruciais, como a Guerra do Vietnã e o Caso Watergate, mas continua pensando no seu amor de infância, Jenny Curran.",
        poster_path: "/d74WpIsH8379TIL4wUxDneRCYv2.jpg",
        release_date: "1994-06-23",
        title: "Forrest Gump: O Contador de Histórias",
        video: false,
        vote_average: 8.5,
        vote_count: 24307,
      },
      {
        adult: false,
        backdrop_path: "/lxD5ak7BOoinRNehOCA85CQ8ubr.jpg",
        genre_ids: [16, 12, 10751, 35],
        id: 862,
        media_type: "movie",
        original_language: "en",
        original_title: "Toy Story",
        overview:
          "Buzz Lightyear é o novo e sofisticado astronauta de brinquedo do garoto Andy. Buzz não imaginava que encontraria um rival: Woody, um cowboy de brinquedo que, dominado pelo ciúme, acredita ter perdido um lugar precioso no coração do seu dono. Os dois brinquedos vivem brigando até que vão parar nas garras do vizinho, um verdadeiro destruidor de brinquedos. Agora, mais do que nunca, Buzz e Woody precisam precisam se unir para escapar do perigo. Com a ajuda de seus amigos da caixa de brinquedos, eles vão viver uma incrível aventura.",
        poster_path: "/6AafgfifXkFS4g2xGJZIwsPQK6P.jpg",
        release_date: "1995-10-30",
        title: "Toy Story: Um Mundo de Aventuras",
        video: false,
        vote_average: 8,
        vote_count: 16451,
      },
      {
        adult: false,
        backdrop_path: "/vxJ08SvwomfKbpboCWynC3uqUg4.jpg",
        genre_ids: [14, 18, 80],
        id: 497,
        media_type: "movie",
        original_language: "en",
        original_title: "The Green Mile",
        overview:
          "Milagres acontecem em lugares inesperados, mesmo no bloco de celas para o corredor da morte na Penitenciária Cold Mountain. Lá, John Coffey, um gentil e gigante prisioneiro com poderes sobrenaturais, traz um senso de espírito e humanidade aos seus guardas e colegas de cela.",
        poster_path: "/14hEqW67IiHlKpzKMLUXyktzZIV.jpg",
        release_date: "1999-12-10",
        title: "À Espera de um Milagre",
        video: false,
        vote_average: 8.5,
        vote_count: 15152,
      },
    ],
    known_for_department: "Acting",
    name: "Tom Hanks",
    popularity: 116.795,
    profile_path: "/xndWFsBlClOJFRdhSt4NBwiPq2o.jpg",
  },
  {
    adult: false,
    gender: 1,
    id: 34486,
    known_for: [
      {
        adult: false,
        backdrop_path: "/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg",
        genre_ids: [878, 28, 12],
        id: 24428,
        media_type: "movie",
        original_language: "en",
        original_title: "The Avengers",
        overview:
          "Loki, o irmão de Thor, ganha acesso ao poder ilimitado do cubo cósmico ao roubá-lo de dentro das instalações da S.H.I.E.L.D. Nick Fury, o diretor desta agência internacional que mantém a paz, logo reúne os únicos super-heróis que serão capazes de defender a Terra de ameaças sem precedentes. Homem de Ferro, Capitão América, Hulk, Thor, Viúva Negra e Gavião Arqueiro formam o time dos sonhos de Fury, mas eles precisam aprender a colocar os egos de lado e agir como um grupo em prol da humanidade.",
        poster_path: "/u49fzmIJHkb1H4oGFTXtBGgaUS1.jpg",
        release_date: "2012-04-25",
        title: "Os Vingadores: The Avengers",
        video: false,
        vote_average: 7.7,
        vote_count: 28304,
      },
      {
        adult: false,
        backdrop_path: "/xXHtSqFx8mLjzNGX9oCKQEx2yTa.jpg",
        genre_ids: [35, 10749],
        id: 3981,
        media_type: "movie",
        original_language: "en",
        original_title: "What Women Want",
        overview:
          "Após sobreviver a um grave acidente, Nick Marshall (Mel Gibson), um executivo machista que trabalha em Chicago, misteriosamente passa a ter o dom de ler os pensamentos das mulheres. Inicialmente ele usa este novo poder para agradar sua chefe, Darcy Maguire (Helen Hunt), mas aos poucos começa a conhecer melhor a intimidade das mulheres e começa a mudar seu estilo de vida.",
        poster_path: "/xj2uHWw6T90M2Ep8ZtTtVC0LcG0.jpg",
        release_date: "2000-12-15",
        title: "Do Que as Mulheres Gostam",
        video: false,
        vote_average: 6.4,
        vote_count: 3456,
      },
      {
        backdrop_path: "/dYJrfkQeqGXeGMMTvYaM43XHce5.jpg",
        first_air_date: "2015-09-21",
        genre_ids: [80, 18, 10759],
        id: 62710,
        media_type: "tv",
        name: "Ponto Cego",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Blindspot",
        overview:
          "Misteriosa mulher é encontrada na Times Square, sem quaisquer lembranças de quem ela é e de como chegou ali. As únicas pistas que ela possui são as tatuagens que cobrem todo o seu corpo. Um agente do FBI passa a ajudá-la enquanto buscam a verdade.",
        poster_path: "/pYyKZZlb3nd5ASbiuIxva718bp2.jpg",
        vote_average: 7.4,
        vote_count: 2233,
      },
    ],
    known_for_department: "Acting",
    name: "Ashley Johnson",
    popularity: 115.619,
    profile_path: "/8s36QwB7Zq3PrbY1W6a6ctTFFoe.jpg",
  },
  {
    adult: false,
    gender: 1,
    id: 1642789,
    known_for: [
      {
        adult: false,
        backdrop_path: "/dKqa850uvbNSCaQCV4Im1XlzEtQ.jpg",
        genre_ids: [35, 80, 9648],
        id: 661374,
        media_type: "movie",
        original_language: "en",
        original_title: "Glass Onion: A Knives Out Mystery",
        overview:
          "O famoso detetive Benoit Blanc vai à Grécia para desvendar um mistério que envolve um bilionário e seu eclético círculo de amizades.",
        poster_path: "/zQJcENHbZUpLQ8RKYt9wTzcXCwv.jpg",
        release_date: "2022-11-23",
        title: "Glass Onion: Um Mistério Knives Out",
        video: false,
        vote_average: 7.1,
        vote_count: 3720,
      },
      {
        backdrop_path: "/onmoNgDVqDJO75eQ93FFyflbJLl.jpg",
        first_air_date: "2020-04-15",
        genre_ids: [10759, 18, 9648],
        id: 100757,
        media_type: "tv",
        name: "Outer Banks",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Outer Banks",
        overview:
          "Em uma ilha onde há pobres e ricos, o jovem John B convoca os três melhores amigos para procurarem por um tesouro lendário ligado ao desaparecimento de seu pai.",
        poster_path: "/rzL0aYsuaoqoYirfzzFSFKZNy3Y.jpg",
        vote_average: 8.5,
        vote_count: 615,
      },
      {
        adult: false,
        backdrop_path: "/3m4XJ9EBKRb9HtA0AbaecBFWjz7.jpg",
        genre_ids: [18],
        id: 472451,
        media_type: "movie",
        original_language: "en",
        original_title: "Boy Erased",
        overview:
          'O jovem Jared, de apenas 19 anos, mora em uma pequena cidade conservadora do Arkansas. Ele é gay e filho de um pastor da Igreja Batista. Em um certo momento de sua vida, Jared é confrontado pela família e precisa escolher entre arriscar perdê-la ou entrar em um programa de terapia que busca tentar "curar" sua homossexualidade.',
        poster_path: "/aMGE7URu5EDZhwhgzP52pGZ8Gkb.jpg",
        release_date: "2018-09-24",
        title: "Boy Erased: Uma Verdade Anulada",
        video: false,
        vote_average: 7,
        vote_count: 1257,
      },
    ],
    known_for_department: "Acting",
    name: "Madelyn Cline",
    popularity: 114.5,
    profile_path: "/qUUfTmpZPhy4zIs8oVk7OINLQqu.jpg",
  },
  {
    adult: false,
    gender: 1,
    id: 115440,
    known_for: [
      {
        backdrop_path: "/oKt4J3TFjWirVwBqoHyIvv5IImd.jpg",
        first_air_date: "2019-06-16",
        genre_ids: [18, 80],
        id: 85552,
        media_type: "tv",
        name: "Euphoria",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Euphoria",
        overview:
          "Um grupo de estudantes do ensino médio lida com diferentes situações típicas da idade como drogas, sexo, busca pela identidade, traumas, comportamento nas redes sociais e amizade.",
        poster_path: "/5mi3aRl16yKmfpQJMzvqN5TXkdA.jpg",
        vote_average: 8.4,
        vote_count: 8574,
      },
      {
        adult: false,
        backdrop_path: "/hJJfo9ktzsK88RU03wtyg9x7Yth.jpg",
        genre_ids: [53],
        id: 645710,
        media_type: "movie",
        original_language: "en",
        original_title: "The Voyeurs",
        overview:
          "Depois de se mudarem para um lindo apartamento no centro de Montreal, um jovem casal começa a se interessar cada vez mais pela vida sexual de seus vizinhos excêntricos do outro lado da rua. O que começa como uma curiosidade inocente aos poucos se transforma em uma obsessão doentia, depois que descobrem que um dos vizinhos está traindo o outro. A tentação e o desejo fazem com que suas vidas se enredem de maneiras inesperadas, levando a consequências mortais.",
        poster_path: "/bOFs0xHCOSTvIUYL0LDd5qcuuDB.jpg",
        release_date: "2021-08-25",
        title: "Observadores",
        video: false,
        vote_average: 6.7,
        vote_count: 622,
      },
      {
        adult: false,
        backdrop_path: "/oRiUKwDpcqDdoLwPoA4FIRh3hqY.jpg",
        genre_ids: [35, 18, 53],
        id: 466272,
        media_type: "movie",
        original_language: "en",
        original_title: "Once Upon a Time… in Hollywood",
        overview:
          "Los Angeles, 1969. Rick Dalton é um ator de TV que, juntamente com seu dublê, está decidido a fazer o nome em Hollywood. Para tanto, ele conhece muitas pessoas influentes na indústria cinematográfica, o que os acaba levando aos assassinatos realizados por Charles Manson na época, entre eles o da atriz Sharon Tate, que na época estava grávida do diretor Roman Polanski.",
        poster_path: "/h30FdikGNkrT6loajaO9G1HHjz0.jpg",
        release_date: "2019-07-24",
        title: "Era Uma Vez em… Hollywood",
        video: false,
        vote_average: 7.4,
        vote_count: 11571,
      },
    ],
    known_for_department: "Acting",
    name: "Sydney Sweeney",
    popularity: 112.975,
    profile_path: "/afr2eoktU4lFYtmtfKo05EbQdXo.jpg",
  },
  {
    adult: false,
    gender: 1,
    id: 9780,
    known_for: [
      {
        adult: false,
        backdrop_path: "/b6ZJZHUdMEFECvGiDpJjlfUWela.jpg",
        genre_ids: [28, 12, 878],
        id: 284054,
        media_type: "movie",
        original_language: "en",
        original_title: "Black Panther",
        overview:
          "O príncipe T'Challa retorna a Wakanda para ser coroado rei. Assumindo o manto de Pantera Negra, ele vai à caça de um vilão que roubou um precioso metal de seu país.",
        poster_path: "/9D40jv8pi9uKnrVDPiN3JYYad72.jpg",
        release_date: "2018-02-13",
        title: "Pantera Negra",
        video: false,
        vote_average: 7.4,
        vote_count: 20427,
      },
      {
        adult: false,
        backdrop_path: "/gYQ30Jer6qMZSKxeDmcibueeq0T.jpg",
        genre_ids: [28, 53],
        id: 267860,
        media_type: "movie",
        original_language: "en",
        original_title: "London Has Fallen",
        overview:
          "O primeiro-ministro britânico morre sob circunstâncias misteriosas, e o funeral atrai todos os líderes do mundo ocidental. O agente secreto Mike Banning descobre uma conspiração para assassinar todos os líderes mundiais presentes.",
        poster_path: "/wazDH9pNQxLzBKCZvN2iMduXxGb.jpg",
        release_date: "2016-03-02",
        title: "Invasão a Londres",
        video: false,
        vote_average: 6.2,
        vote_count: 4229,
      },
      {
        adult: false,
        backdrop_path: "/58r049aVTO1KjAYVuWJr0KgG5nY.jpg",
        genre_ids: [12, 28, 53, 878],
        id: 44912,
        media_type: "movie",
        original_language: "en",
        original_title: "Green Lantern",
        overview:
          "Hal Jordan, um vaidoso piloto de testes, recebe um poderoso anel e é recrutado por um esquadrão intergaláctico chamado Lanterna Verde para lutar contra um feroz inimigo que ameaça acabar com o equilíbrio do universo.",
        poster_path: "/xfZ1p8nNavu5sbLcyrB1FgOYK23.jpg",
        release_date: "2011-06-16",
        title: "Lanterna Verde",
        video: false,
        vote_average: 5.2,
        vote_count: 6573,
      },
    ],
    known_for_department: "Acting",
    name: "Angela Bassett",
    popularity: 112.294,
    profile_path: "/7Oz53NKdglRzAzI2MKjM3eQXwn.jpg",
  },
];

export function PopularPersonList({
  personList,
  loadingPersonDetails,
}: PopularPersonListProps) {
  return (
    <div className='w-full mt-2'>
      {personList && personList?.length > 0 && !loadingPersonDetails ? (
        <div className='w-full h-list-md rounded'>
          <ScrollableComponent listSize={personList?.length}>
            <ul className='h-full flex flex-row items-center' role='list'>
              {personList?.map((person: IPerson, index) => (
                <ListItem
                  key={person.id}
                  url={`person/${person.id}`}
                  poster_path={person.profile_path}
                  title={person.name}
                />
              ))}
            </ul>
          </ScrollableComponent>
        </div>
      ) : null}
    </div>
  );
}
